#!/bin/sh
cd stage
find . | cpio -H newc -o | gzip >../uInitramfs.cpio.gz
cd ..
mkimage -A arm -O linux -T ramdisk -C gzip -a 0x00e00000 -e 0x00e00000 -n DNS325-Initramfs -d uInitramfs.cpio.gz uInitramfs
